### PR TITLE
feat : rule & quiz page

### PR DESCRIPTION
**Pull request by mikesch803**

### CODE REVIEW

**Comment by mikesch803** [comment]
https://laughing-euclid-3a1a03.netlify.app/pages/rules.html

**Review by ApurvaSawant11 — APPROVED** [review]
Looks good to me!

Just add a cursor pointer for the quiz options

**Comment by mikesch803** [comment]
> Looks good to me!
> 
> Just add a cursor pointer for the quiz options

added

**Comment by hsnice16** [comment]
Great work, man. UI is clean and the color choice is amazing. Code looks good too.

**Review by hsnice16 — APPROVED** [review]

**Pull request merged**
